"""Conversation dataset for Qwen3-VL LoRA fine-tuning.

Training data: 3-5K synthetic conversations generated by Gemini,
covering 7 types (see Kien_truc_v3.1.md §4.2):
  - ask_missing_info (hỏi lại khi thiếu thông tin)
  - body_analysis (phân tích ảnh body)
  - recommend_explain (recommend + giải thích)
  - polite_decline (từ chối lịch sự)
  - multi_turn (hội thoại nhiều lượt)
  - edge_case (tình huống khó)
  - tool_calling (gọi search_outfits)

Spot-check ~5% of generated conversations before training.

Implemented in Sprint 6-7.
"""

from __future__ import annotations


def load_conversation_dataset(
    jsonl_path: str,
    tokenizer: object,
    max_length: int = 2048,
) -> object:
    """Load and tokenise conversation JSONL for SFT training.

    JSONL format per line:
    {"conversations": [{"role": "system", "content": "..."}, {"role": "user", ...}, ...]}
    """
    raise NotImplementedError("Implement in Sprint 6-7: LoRA training dataset")
