"""Outfit and tool-call hallucination detection.

After Qwen3-VL generates a response, validate referenced outfit IDs, tool-call
payloads, and explicit size mentions against runtime constraints.
"""

from __future__ import annotations

import json
import re
from collections.abc import Collection
from typing import Any

from outfitmatch.stylist.tools import TOOL_CALL_PATTERN, validate_tool_call_payload

# Matches OF_ followed by >=5 alnum chars (legacy OF_00001 digits OR the new
_OUTFIT_ID_RE = re.compile(r"\bOF_[0-9A-Za-z]{5,}\b")
# Size only counts when explicitly written as "size X" / "cỡ X" to keep false
# positives near zero in normal Vietnamese prose.
_SIZE_MENTION_RE = re.compile(r"\b(?:size|cỡ)\s+([A-Za-z]{1,3}|\d{1,3})\b", re.IGNORECASE)


def extract_outfit_ids(text: str) -> list[str]:
    """Return all outfit IDs (OF_NNNNN) found in text, preserving order."""
    return _OUTFIT_ID_RE.findall(text)


def validate_response(response: str, valid_ids: Collection[str]) -> tuple[bool, list[str]]:
    """Check that every outfit ID in the response exists in the Knowledge Base.

    Args:
        response: Raw text generated by Qwen3-VL.
        valid_ids: Set of outfit_id values that exist in the KB.

    Returns:
        (is_valid, invalid_ids) — is_valid is False if any hallucinated ID found.

    Example:
        ok, bad = validate_response("Tôi gợi ý OF_00001 và OF_99999.", {"OF_00001"})
        # ok=False, bad=["OF_99999"]
    """
    found = extract_outfit_ids(response)
    invalid = [i for i in found if i not in valid_ids]
    return len(invalid) == 0, invalid


def extract_tool_calls(text: str) -> list[dict[str, Any]]:
    """Return all valid JSON tool-call payloads found in text, preserving order."""
    payloads: list[dict[str, Any]] = []
    for match in TOOL_CALL_PATTERN.finditer(text):
        try:
            payload = json.loads(match.group(1))
        except json.JSONDecodeError:
            continue
        if isinstance(payload, dict):
            payloads.append(payload)
    return payloads


def validate_tool_calls(text: str) -> tuple[bool, list[str]]:
    """Validate every tool-call block found in text against the canonical schema."""
    errors: list[str] = []
    for index, match in enumerate(TOOL_CALL_PATTERN.finditer(text)):
        try:
            payload = json.loads(match.group(1))
        except json.JSONDecodeError as exc:
            errors.append(f"tool_call[{index}] invalid JSON: {exc.msg}")
            continue
        if not isinstance(payload, dict):
            errors.append(f"tool_call[{index}] payload must be an object")
            continue
        ok, payload_errors = validate_tool_call_payload(payload)
        errors.extend(f"tool_call[{index}] {error}" for error in payload_errors)
        if not ok and not payload_errors:
            errors.append(f"tool_call[{index}] invalid payload")
    return len(errors) == 0, errors


def extract_size_mentions(text: str) -> list[str]:
    """Return size tokens written as ``size X`` / ``cỡ X`` in upper-case order."""
    return [m.group(1).upper() for m in _SIZE_MENTION_RE.finditer(text)]


def validate_sizes(response: str, available_sizes: Collection[str]) -> tuple[bool, list[str]]:
    """Check every explicitly-mentioned size exists in the real available sizes."""
    allowed = {str(s).upper() for s in available_sizes}
    found = extract_size_mentions(response)
    invalid = [size for size in found if size not in allowed]
    return len(invalid) == 0, invalid
