"""Outfit ID hallucination detection.

After Qwen3-VL generates a response, extract all outfit_id references and
verify each one exists in the Knowledge Base. Any unrecognised ID is flagged
as a hallucination and must NOT be shown to the user.
"""
from __future__ import annotations

import re
from typing import Collection

# Matches OF_XXXXX where X is a digit — adjust if outfit_id format changes.
_OUTFIT_ID_RE = re.compile(r"\bOF_\d{5,}\b")


def extract_outfit_ids(text: str) -> list[str]:
    """Return all outfit IDs (OF_NNNNN) found in text, preserving order."""
    return _OUTFIT_ID_RE.findall(text)


def validate_response(
    response: str, valid_ids: Collection[str]
) -> tuple[bool, list[str]]:
    """Check that every outfit ID in the response exists in the Knowledge Base.

    Args:
        response: Raw text generated by Qwen3-VL.
        valid_ids: Set of outfit_id values that exist in the KB.

    Returns:
        (is_valid, invalid_ids) — is_valid is False if any hallucinated ID found.

    Example:
        ok, bad = validate_response("Tôi gợi ý OF_00001 và OF_99999.", {"OF_00001"})
        # ok=False, bad=["OF_99999"]
    """
    found = extract_outfit_ids(response)
    invalid = [i for i in found if i not in valid_ids]
    return len(invalid) == 0, invalid
