"""OutfitTransformer compatibility re-scoring.

REQUIRED: every outfit generated by generation.py MUST pass through rescore_outfits()
before being stored in the KB. FITB/beam is locally greedy — not globally optimal.

Implemented in Sprint 3-4. See Kien_truc_v3.1.md §3.4 Bước 4.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from outfitmatch.kb.schema import OutfitRecord


def rescore_outfits(
    outfits: list[OutfitRecord],
    encoder: Any,
    score_threshold: float = 0.0,
) -> list[OutfitRecord]:
    """Re-score all outfits with OT compatibility; filter by score_threshold.

    Args:
        outfits: Candidates from generation.py (compatibility_score may be 0.0).
        encoder: OutfitTransformer-labse encoder.
        score_threshold: Determined empirically in Sprint 3 from score distribution.
                         Start at 0.0, analyse histogram, then raise to prune low-quality.

    Returns:
        Outfits with compatibility_score populated, filtered above threshold.
    """
    raise NotImplementedError("Implement in Sprint 3-4: OT re-scoring")
