"""OutfitTransformer compatibility re-scoring.

REQUIRED: every outfit generated by generation.py MUST pass through rescore_outfits()
before being stored in the KB. FITB/beam is locally greedy — not globally optimal.

Until the full OT image/text feature extractor is wired, ``HeuristicOutfitScorer``
provides a deterministic baseline adapter with the same ``score_outfit`` interface.
It is useful for smoke-generating KB candidates and for tests; final grading should
swap it for the frozen OutfitTransformer-labse scorer.
"""

from __future__ import annotations

import hashlib
import math
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from outfitmatch.kb.schema import ItemRecord, OutfitRecord


class HeuristicOutfitScorer:
    """Deterministic baseline encoder/scorer for offline outfit-combination smoke runs."""

    def __init__(self, embedding_dim: int = 128) -> None:
        self.embedding_dim = embedding_dim

    def encode_item(self, item: ItemRecord) -> list[float]:
        """Encode an item into a normalized hashing-vector embedding."""
        text = "|".join(
            [
                item.item_id,
                item.category,
                str(item.store.get("title_vi", "")),
                str(item.store.get("desc_vi", "")),
                ",".join(str(v) for v in item.store.get("colors", [])),
            ]
        )
        vector = [0.0] * self.embedding_dim
        for token in text.lower().split():
            digest = hashlib.blake2b(token.encode("utf-8"), digest_size=8).digest()
            idx = int.from_bytes(digest[:4], "big") % self.embedding_dim
            sign = 1.0 if digest[4] % 2 == 0 else -1.0
            vector[idx] += sign
        norm = math.sqrt(sum(v * v for v in vector)) or 1.0
        return [v / norm for v in vector]

    def score_outfit(self, items: list[ItemRecord]) -> float:
        """Return a bounded compatibility proxy in ``[0, 1]``.

        The heuristic rewards valid category structure, a moderate total price,
        useful color repetition, and availability of VN store URLs. It intentionally
        avoids user-query similarity; retrieval remains metadata-filter + score-sort.
        """
        categories = {item.category for item in items}
        valid_rule = {"top", "bottom", "shoes"} <= categories or {"dress", "shoes"} <= categories
        score = 0.35 if valid_rule else 0.05

        prices = [int(item.store.get("price_vnd") or 0) for item in items]
        total = sum(prices)
        if 300_000 <= total <= 1_800_000:
            score += 0.20
        elif 150_000 <= total <= 3_000_000:
            score += 0.10

        colors: list[str] = []
        for item in items:
            colors.extend(str(v).lower() for v in item.store.get("colors", []) if str(v))
        if colors:
            repeated = len(colors) - len(set(colors))
            score += min(0.15, repeated * 0.05) + 0.05

        stores_with_url = sum(1 for item in items if item.store.get("product_url"))
        score += 0.15 * (stores_with_url / max(1, len(items)))

        optional_count = len(categories & {"outerwear", "bag", "accessory"})
        score += min(0.10, optional_count * 0.04)
        return max(0.0, min(1.0, round(score, 6)))


def rescore_outfits(
    outfits: list[OutfitRecord],
    encoder: Any,
    score_threshold: float = 0.0,
) -> list[OutfitRecord]:
    """Re-score all outfits with an OT-compatible scorer; filter by threshold.

    Args:
        outfits: Candidates from generation.py (compatibility_score may be 0.0).
        encoder: Object exposing ``score_outfit(items)``.
        score_threshold: Minimum compatibility score to keep.

    Returns:
        Outfits with ``compatibility_score`` populated, filtered above threshold.
    """
    if not hasattr(encoder, "score_outfit"):
        raise TypeError("encoder must provide score_outfit(items)")

    kept: list[OutfitRecord] = []
    for outfit in outfits:
        score = float(encoder.score_outfit(outfit.items))
        outfit.compatibility_score = max(0.0, min(1.0, score))
        if outfit.compatibility_score >= score_threshold:
            kept.append(outfit)
    return kept
